# Azure Pipeline para Build (CI)
# RM557245 - Vitor Kenzo Mizumoto
# RM556760 - Adriano Barutti Pessuto

trigger:
  branches:
    include:
    - main # Gatilho: rodar apenas quando houver merge na main
  paths:
    include:
    - '**/*.cs'
    - '**/*.csproj'
    - '**/*.sln'
    - 'azure-pipeline.yml'

# A política de branch que você configurou (Fase 1) garante 
# que isso só rodará APÓS um PR, cumprindo o Req. 4.4
pr: none 

variables:
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'
  dotnetSdkVersion: '9.0.x' # Verifique a versão do seu projeto

stages:
- stage: Build
  displayName: 'Build e Testes'
  jobs:
  - job: BuildJob
    displayName: 'Build, Restore, Test e Publish'
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UseDotNet@2
      displayName: 'Instalar .NET SDK $(dotnetSdkVersion)'
      inputs:
        packageType: 'sdk'
        version: $(dotnetSdkVersion)

    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build do projeto'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'Executar testes (da pasta /Tests)'
      inputs:
        command: 'test'
        projects: '**/MinhaApiOracle.Tests.csproj' # Caminho exato para seu projeto de teste
        arguments: '--configuration $(buildConfiguration) --no-build --logger "trx;LogFileName=test-results.trx"'
      
    - task: PublishTestResults@2
      displayName: 'Publicar resultados de testes'
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*.trx'
        testRunTitle: 'Testes XUnit'
      condition: succeededOrFailed() # Publica resultados mesmo se os testes falharem

    # Esta é a etapa de Publicação da API (NÃO dos testes)
    - task: DotNetCoreCLI@2
      displayName: 'Publish da aplicação (API)'
      inputs:
        command: 'publish'
        publishWebProjects: false # Falso, para podermos especificar o projeto
        projects: '**/MinhaApiOracle.csproj' # Caminho EXATO para seu projeto da API
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build'
        zipAfterPublish: true # Gera o .zip que o Release vai usar
      condition: succeeded() # Só publica se testes e build passarem

    # Esta tarefa publica o .zip como um "Artefato" chamado "drop"
    - task: PublishBuildArtifacts@1
      displayName: 'Publicar artefato (drop)'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop' # Nome do artefato
        publishLocation: 'Container'
      condition: succeeded()