# Azure Pipeline para Build e Deploy
# RM557245 - Vitor Kenzo Mizumoto
# RM556760 - Adriano Barutti Pessuto

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - '**/*.cs'
    - '**/*.csproj'
    - '**/*.sln'
    - 'azure-pipeline.yml'

pr: none  # Build deve ser acionado somente após Merge via PR

variables:
  azureSubscription: 'ConexaoAzureStudents'
  webAppName: 'web-minha-api-oracle'
  resourceGroup: 'rg-minha-api-oracle'
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: 'Build e Testes'
  jobs:
  - job: BuildJob
    displayName: 'Build, Restore, Test e Publish'
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UseDotNet@2
      displayName: 'Instalar .NET 9.0 SDK'
      inputs:
        packageType: 'sdk'
        version: '9.0.x'

    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build do projeto'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: DotNetCoreCLI@2
      displayName: 'Executar testes (XUnit)'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"'
      continueOnError: true

    - task: PublishTestResults@2
      displayName: 'Publicar resultados de testes'
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '**/*.trx'
        testRunTitle: 'Testes XUnit'
        failTaskOnFailedTests: false
      condition: always()
      continueOnError: true

    - task: DotNetCoreCLI@2
      displayName: 'Publish da aplicação'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publicar artefatos'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy para Azure Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy no Azure Web App'
    pool:
      vmImage: $(vmImageName)
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/**/*.zip'
              deploymentMethod: 'auto'

