// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhaApiOracle.Data;

#nullable disable

namespace MinhaApiOracle.Migrations
{
    [DbContext(typeof(AppDb))]
    [Migration("20251113134808_NovaEstruturaBancoDados")]
    partial class NovaEstruturaBancoDados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinhaApiOracle.Models.Certificado", b =>
                {
                    b.Property<string>("IdCertificado")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ID_CERTIFICADO");

                    b.Property<string>("CodigoValidacao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CODIGO_VALIDACAO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<DateTime>("DtEmissao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_EMISSAO");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int")
                        .HasColumnName("ID_CURSO");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdCertificado");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("MinhaApiOracle.Models.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_CURSO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("NOME_CURSO");

                    b.Property<int>("QtHoras")
                        .HasColumnType("int")
                        .HasColumnName("QT_HORAS");

                    b.HasKey("IdCurso");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("MinhaApiOracle.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_EMPRESA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("EmailEmpresa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL_EMPRESA");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("MinhaApiOracle.Models.LogAuditoria", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_LOG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("DataOperacao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DATA_OPERACAO");

                    b.Property<string>("DsOperacao")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("DS_OPERACAO");

                    b.Property<string>("NmUsuarioDb")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NM_USUARIO_DB");

                    b.Property<string>("NomeTabela")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NOME_TABELA");

                    b.HasKey("IdLog");

                    b.ToTable("LogAuditorias");
                });

            modelBuilder.Entity("MinhaApiOracle.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USUARIO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<DateTime>("Cadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("CADASTRO");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("CPF");

                    b.Property<string>("EmailUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EMAIL_USUARIO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SENHA");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MinhaApiOracle.Models.Vaga", b =>
                {
                    b.Property<int>("IdVaga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_VAGA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVaga"));

                    b.Property<string>("DescricaoVaga")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO_VAGA");

                    b.Property<DateTime?>("DtPublicacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_PUBLICACAO");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("ID_EMPRESA");

                    b.Property<string>("NomeVaga")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NOME_VAGA");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("SALARIO");

                    b.HasKey("IdVaga");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Vagas");
                });

            modelBuilder.Entity("MinhaApiOracle.Models.Certificado", b =>
                {
                    b.HasOne("MinhaApiOracle.Models.Curso", "Curso")
                        .WithMany("Certificados")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhaApiOracle.Models.Usuario", "Usuario")
                        .WithMany("Certificados")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MinhaApiOracle.Models.Vaga", b =>
                {
                    b.HasOne("MinhaApiOracle.Models.Empresa", "Empresa")
                        .WithMany("Vagas")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("MinhaApiOracle.Models.Curso", b =>
                {
                    b.Navigation("Certificados");
                });

            modelBuilder.Entity("MinhaApiOracle.Models.Empresa", b =>
                {
                    b.Navigation("Vagas");
                });

            modelBuilder.Entity("MinhaApiOracle.Models.Usuario", b =>
                {
                    b.Navigation("Certificados");
                });
#pragma warning restore 612, 618
        }
    }
}
