-- Script de criação do banco de dados
-- Sistema de Gestão de Certificados e Vagas de Emprego
-- RM557245 - Vitor Kenzo Mizumoto
-- RM556760 - Adriano Barutti Pessuto

-- Tabela T_USUARIOS
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'T_USUARIOS')
BEGIN
    CREATE TABLE T_USUARIOS (
        ID_USUARIO NUMERIC(10) IDENTITY(1,1) PRIMARY KEY,
        NOME VARCHAR(100) NOT NULL,
        EMAIL_USUARIO VARCHAR(100) NOT NULL,
        SENHA VARCHAR(100) NOT NULL,
        CADASTRO DATE NOT NULL DEFAULT GETDATE(),
        CPF VARCHAR(14) NOT NULL,
        CONSTRAINT UK_CPF_USUARIO UNIQUE (CPF)
    );
    PRINT 'Tabela T_USUARIOS criada com sucesso.';
END
GO

-- Tabela T_CURSO
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'T_CURSO')
BEGIN
    CREATE TABLE T_CURSO (
        ID_CURSO NUMERIC(10) IDENTITY(1,1) PRIMARY KEY,
        NOME_CURSO VARCHAR(150) NOT NULL,
        DESCRICAO NVARCHAR(MAX),
        QT_HORAS NUMERIC(4) NOT NULL
    );
    PRINT 'Tabela T_CURSO criada com sucesso.';
END
GO

-- Tabela T_CERTIFICADO
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'T_CERTIFICADO')
BEGIN
    CREATE TABLE T_CERTIFICADO (
        ID_CERTIFICADO VARCHAR(10) PRIMARY KEY,
        DT_EMISSAO DATE NOT NULL,
        DESCRICAO VARCHAR(200),
        CODIGO_VALIDACAO VARCHAR(50),
        ID_USUARIO NUMERIC(10) NOT NULL,
        ID_CURSO NUMERIC(10) NOT NULL,
        CONSTRAINT FK_CERTIFICADO_USUARIO FOREIGN KEY (ID_USUARIO) 
            REFERENCES T_USUARIOS(ID_USUARIO),
        CONSTRAINT FK_CERTIFICADO_CURSO FOREIGN KEY (ID_CURSO) 
            REFERENCES T_CURSO(ID_CURSO)
    );
    PRINT 'Tabela T_CERTIFICADO criada com sucesso.';
END
GO

-- Tabela T_EMPRESA
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'T_EMPRESA')
BEGIN
    CREATE TABLE T_EMPRESA (
        ID_EMPRESA NUMERIC(10) IDENTITY(1,1) PRIMARY KEY,
        RAZAO_SOCIAL VARCHAR(150) NOT NULL,
        CNPJ VARCHAR(14) NOT NULL,
        EMAIL_EMPRESA VARCHAR(100),
        CONSTRAINT UK_EMP_CNPJ UNIQUE (CNPJ)
    );
    PRINT 'Tabela T_EMPRESA criada com sucesso.';
END
GO

-- Tabela T_VAGA
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'T_VAGA')
BEGIN
    CREATE TABLE T_VAGA (
        ID_VAGA NUMERIC(10) IDENTITY(1,1) PRIMARY KEY,
        NOME_VAGA VARCHAR(100) NOT NULL,
        DESCRICAO_VAGA NVARCHAR(MAX),
        SALARIO DECIMAL(10,2),
        DT_PUBLICACAO DATE,
        ID_EMPRESA NUMERIC(10) NOT NULL,
        CONSTRAINT FK_VAGA_EMPRESA FOREIGN KEY (ID_EMPRESA) 
            REFERENCES T_EMPRESA(ID_EMPRESA)
    );
    PRINT 'Tabela T_VAGA criada com sucesso.';
END
GO

-- Tabela T_LOG_AUDITORIA
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'T_LOG_AUDITORIA')
BEGIN
    CREATE TABLE T_LOG_AUDITORIA (
        ID_LOG NUMERIC(10) IDENTITY(1,1) PRIMARY KEY,
        NOME_TABELA VARCHAR(50),
        DS_OPERACAO CHAR(1),
        DATA_OPERACAO VARCHAR(50),
        NM_USUARIO_DB VARCHAR(100)
    );
    PRINT 'Tabela T_LOG_AUDITORIA criada com sucesso.';
END
GO

PRINT 'Script de criação do banco de dados executado com sucesso!';
GO

